#!/usr/bin/env bash
# Regenerate Samba share manifest and reload smbd (fixes glob include on Samba 4.x).
set -euo pipefail

SHARES_D="/etc/samba/shares.d"
MANIFEST="${SHARES_D}/00-manifest.conf"
SMB_CONF="/etc/samba/smb.conf"

{
  echo "# Auto-generated by FrogsWork — lists dynamic share fragments"
  for path in "${SHARES_D}"/*.conf; do
    base="$(basename "${path}")"
    case "${base}" in
      00-*) continue ;;
    esac
    echo "include = ${path}"
  done
} > "${MANIFEST}.tmp"
install -m 644 "${MANIFEST}.tmp" "${MANIFEST}"
rm -f "${MANIFEST}.tmp"

if grep -q 'shares.d/\*.conf' "${SMB_CONF}"; then
  sed -i 's|include = /etc/samba/shares.d/\*.conf|include = /etc/samba/shares.d/00-manifest.conf|' "${SMB_CONF}"
fi

testparm -s >/dev/null
systemctl reload smbd
echo "Samba manifest rebuilt and smbd reloaded."
